name: Benchmark

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Performance Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Run benchmarks
        run: |
          cargo bench --bench throughput --bench latency
          echo "Benchmarks completed successfully"
        timeout-minutes: 15
      
      - name: Prepare benchmark results
        run: |
          mkdir -p benchmark-results
          cp -r target/criterion benchmark-results/
          
          # Copy the index template if it exists
          if [ -f docs/benchmark-template.html ]; then
            cp docs/benchmark-template.html benchmark-results/index.html
          else
            # Generate a basic index if template doesn't exist
            echo '<!DOCTYPE html><html><head><title>FeOxDB Benchmarks</title></head>' > benchmark-results/index.html
            echo '<body><h1>FeOxDB Benchmarks</h1>' >> benchmark-results/index.html
            echo '<p><a href="criterion/report/index.html">View Criterion Reports</a></p>' >> benchmark-results/index.html
            echo '</body></html>' >> benchmark-results/index.html
          fi
          
      - name: Generate benchmark summary
        run: |
          echo "# FeOxDB Benchmark Results" > benchmark-results/summary.md
          echo "" >> benchmark-results/summary.md
          echo "## Latest Performance Metrics" >> benchmark-results/summary.md
          echo "" >> benchmark-results/summary.md
          echo "### Throughput Benchmarks" >> benchmark-results/summary.md
          find target/criterion -name "estimates.json" | while read f; do
            name=$(echo $f | sed 's/.*criterion\/\(.*\)\/.*estimates.json/\1/' | sed 's/\//-/g')
            mean=$(jq -r '.mean.point_estimate' $f 2>/dev/null || echo 'N/A')
            if [ "$mean" != "N/A" ]; then
              echo "- **$name**: $mean" >> benchmark-results/summary.md
            fi
          done
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./benchmark-results
          destination_dir: benchmarks
          keep_files: false
      
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: FeOxDB Benchmarks
          tool: 'cargo'
          output-file-path: target/criterion/**/*.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          alert-threshold: '150%'
          comment-always: false
          benchmark-data-dir-path: 'dev/bench'
          gh-pages-branch: gh-pages
      
      - name: Upload benchmark artifacts
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: benchmark-results/